#ifndef BOX_DEFINES_INCLUDE
#define BOX_DEFINES_INCLUDE

#define BOX_FTYP		"ftyp"
#define BOX_MOOV		"moov"
#define BOX_MVHD		"mvhd"
#define BOX_TRAK		"trak"
#define BOX_TKHD		"tkhd"
#define BOX_EDTS		"edts"
#define BOX_ELST		"elst"
#define BOX_MDIA		"mdia"
#define BOX_MDHD		"mdhd"
#define BOX_HDLR		"hdlr"
#define BOX_MINF		"minf"
#define BOX_SMHD		"smhd"
#define BOX_VMHD		"vmhd"
#define BOX_DINF		"dinf"
#define BOX_DREF		"dref"
#define BOX_URL     	"url "
#define BOX_CTTS        "ctts"
#define BOX_URN	        "urn "
#define BOX_STBL		"stbl"
#define BOX_UDTA		"udta"
#define BOX_STSD		"stsd"
#define BOX_STTS		"stts"
#define BOX_STSC		"stsc"
#define BOX_STSS		"stss"
#define BOX_STSZ		"stsz"
#define BOX_STCO		"stco"
#define BOX_AVC1		"avc1"
#define BOX_AVCC		"avcC"
#define BOX_MP4A		"mp4a"
#define BOX_ESDS		"esds"
#define BOX_FREE		"free"
#define BOX_MDAT		"mdat"
#define BOX_UUID        "uuid"
#define BOX_PDIN        "pdin"
#define BOX_UNKNOW      "unknow"



#endif